### PR TITLE
Don't translate termcodes twice on input

### LINKED ISSUE #325: Custom surround `<M-]>` doesn't work since v2.1.3
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1693350652
```

### Plugin Version

Tagged (Stable)

### Minimal Configuration

(note I use these in Lua files, to ease changing `[[ ... ]]`-based strings)
```lua
require('nvim-surround').setup {
  surrounds = {
    ["<M-[>"] = {
      add = { "[[ ", " ]]" },
      find = vim.pesc"[[" .. ".-" .. vim.pesc"]]",
      delete = (
        "^" ..
        "(" .. vim.pesc"[[" .. "%s*)()" .. -- removes any number of spaces
        ".-" ..
        "(%s*" .. vim.pesc"]]" .. ")()" .. -- removes any number of spaces
        "$"
      )
    },
    ["<M-]>"] = {
      add = { "[[", "]]" },
      find = vim.pesc"[[" .. ".-" .. vim.pesc"]]",
      delete = (
        "^" ..
        "(" .. vim.pesc"[[" .. ")()" ..
        ".-" ..
        "(" .. vim.pesc"]]" .. ")()" ..
        "$"
      )
    }
  }
}
```

### Sample Buffer

```
[[  foobar  ]]
```

### Keystroke Sequence

0. `fb`
1. `cs` `<M-[>` `<M-]>`
2. `ds` `<M-]>`

### Expected behavior

- After 1., buffer should be `[[foobar]]`
- After 2., buffer should be `foobar`

### Actual behavior

Nothing happens

### Additional context

I bisected the issue to https://github.com/kylechui/nvim-surround/commit/cfa2da7f469f1e759f2a961bc25fa4ccfe1795c2

And neovim devs mentioned to me that calling `nvim_replace_termcodes` on the result of `getcharstr` is wrong, the output of `getcharstr` is already the raw chars!
See https://github.com/neovim/neovim/issues/29034

### PR DESCRIPTION
**Pull request by bew**
`getcharstr()` already returns raw internal termcodes, it is wrong to call nvim_replace_termcodes on its result.

This effectively reverts PR #273

refs: neovim/neovim#29034
fixes #325

---
The original PR #273 was supposedly fixing the issue #271, @Mango0x45 could you check if you now get that problem back or if #318 was the actual correct fix ?

### CODE REVIEW

**Comment by kylechui** [comment]
Thanks for the PR + bug analysis! Do you mind adding two unit tests to `config_spec.lua`? One for a multi-byte character like the ASCII quote `’`, and one for an "interpreted" multi-byte character like `<M-[>`? Just so we prevent these issues from cropping up again down the line.

File: tests/configuration_spec.lua [hunk 1]
```diff
@@ -54,6 +54,43 @@ describe("configuration", function()
...
+                -- interpreted multi-byte quote
+                ["<M-]>"] = {
+                    add = { "[[", "]]" },
+                    delete = "^(%[%[)().-(%]%])()$",
+                }
+            }
+        })
+        set_lines({ "hey! hello world" })
+        set_curpos({ 1, 7 })
+        -- note: `:execute` necessary to interpret `\<M-]>` as raw termcodes
```
Comment (kylechui) [inline tests/configuration_spec.lua:87]: Do you mind reverting to `:normal` and just creating a local mapping using `vim.api.nvim_replace_termcodes`, similarly to how I've done in the first two lines of this file? For example,
```lua
local meta_close_bracket = vim.api.nvim_replace_termcodes(...)
vim.cmd("normal ysiw" .. meta_close_bracket)
```

File: tests/configuration_spec.lua [hunk 2]
```diff
@@ -54,6 +54,43 @@ describe("configuration", function()
         })
     end)
 
+    it("can define and use multi-byte mappings", function()
+        require("nvim-surround").setup({
+            surrounds = {
+                -- multi-byte linguistic quote
+                ["’"] = {
+                    add = { "’", "’" },
+                    delete = "^()().-()()$",
```
Comment (kylechui) [inline tests/configuration_spec.lua:63]: I'm honestly a bit confused as for how this unit test is working, since it seems like you're not actually putting anything into the capture groups *to* be deleted. It should be `^(.)().-(.)()$` instead.

**Review by kylechui — CHANGES_REQUESTED** [review]

**Comment by kylechui** [comment]
Oh yeah can you also either run `stylua` on the project, or [add some trailing commas to appease the formatter](https://github.com/kylechui/nvim-surround/actions/runs/9307300601/job/25618290816?pr=326)?

File: tests/configuration_spec.lua (hunk 1 above)
Comment (bew) [reply tests/configuration_spec.lua:87]: Yes that's actually what I ended up with, since I couldn't make it work locally... Well actually it still doesn't work but not sure why yet ^^'

**Comment by bew** [comment]
Could you please avoid force pushing while I'm still working on it 😬

File: tests/configuration_spec.lua (hunk 2 above)
Comment (kylechui) [reply tests/configuration_spec.lua:63]: Oh nevermind the unit test simply isn't passing :grinning:

**Comment by kylechui** [comment]
Ah my bad, I didn't realize the rebasing was force-pushing the branch :sob: Sorry!

File: tests/configuration_spec.lua (hunk 2 above)
Comment (bew) [reply tests/configuration_spec.lua]: I agree, I added `’` where relevant, should make more sense now

File: tests/configuration_spec.lua [hunk 3]
```diff
@@ -54,6 +54,43 @@ describe("configuration", function()
...
+        vim.cmd("normal ds’")
+        check_lines({ "hey! hello world" })
+    end)
+
+    it("can define and use 'interpreted' multi-byte mappings", function()
+        require("nvim-surround").setup({
+            surrounds = {
+                -- interpreted multi-byte
+                ["<M-]>"] = {
+                    add = { "[[", "]]" },
```
Comment (kylechui) [inline tests/configuration_spec.lua:80]: I think you forgot to specify the `find` key here, since the default will incorrectly search for `<M-]>.-<M-]>`; try
```lua
                    add = { "[[", "]]" },
                    find = "%[%b[]%]",
                    delete = "^(%[%[)().-(%]%])()$",
```

Comment (bew) [reply tests/configuration_spec.lua:80]: Yay that works \o/

**Comment by bew** [comment]
Should be good now :smiley:

**Comment by kylechui** [comment]
:fire: Thanks for the contribution!

**Comment by bew** [comment]
Thanks for review & merge, I love this plugin :heart: 
I particularly love the selection system you did here and wish it'll be a builtin in neovim some day
(have you ever though about it? 🤔)

**Comment by bew** [comment]
What I like about your impl is that Lua code can get the boundaries of a motion or a text object, and do something with it.

I had a few times wanted for such function be builtin, for example to request where would `e` go without actually doing it, to replicate the `e` normal motion in insert mode with `<M-e>` (I already have `<M-b>` & `<M-w>` mapped to `<C-Left>` & `<C-Right>`)
(but I actually can't really do it anyway without breaking last-insert-change repetitions with `.` afaik ><)

**Comment by kylechui** [comment]
Ah I see you were referring to the interface, not the implementation. It's honestly not too complicated for built-in Vim motions: the "hack" boils down to saving the cursor position, performing the motions, then restoring the cursor position at the end. It's by no means perfect (one thing that comes to mind is if the motion sends the cursor off-screen then it's hard to restore it properly), but works fine enough most of the time. I honestly never really considered that as something that could be upstreamed, but now that you mention it it would be nice to just use something like `vim.get_motion("a)")` or something like that.

I was under the impression that one can already extend visual selections using text objects, so I'm not entirely sure what that means :thinking:
